# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title.html
# relative_permalinks: true

# Setup
title:               danielsjourney
tagline:             seeking stories beauty meaning
url:                 http://danielsjourney.com
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Daniel Miller
  url:               https://twitter.com/dealingwith
  email:             dealingwith@gmail.com

gems: [jekyll-paginate]
